FROM apache/airflow:2.11.0-python3.12

COPY requirements.txt /tmp/requirements.txt
COPY requirements-airflow.txt /tmp/requirements-airflow.txt

RUN pip install --no-cache-dir -r /tmp/requirements.txt && \
    pip install --no-cache-dir -r /tmp/requirements-airflow.txt
